all:
  scryer-prolog autopsy.pl -g print -- ./logs/*.log

download:
  scryer-prolog ./download-logs.pl -g run -t halt

test:
  ./test.sh

unknowns:
  find ./logs -name '*.log' | xargs scryer-prolog autopsy.pl -g unknown -- | cut -d '|' -f 1 | sort | uniq -c | sort -nr
