all:
  scryer-prolog autopsy.pl -g print -- ./logs/*.log

test:
  ./test.sh

unknowns:
  find ./logs -name '*.log' | xargs scryer-prolog autopsy.pl -g unknown -- | cut -d '|' -f 1 | sort | uniq -c | sort -nr
